### ISSUE TITLE
Persistent Volume is not released after done building the pipelineruns

### ISSUE THREAD

**Issue by tam512** [kabanero-io/kabanero-pipelines#123]
- Using OCP 4.2 with Kabanero Operator 0.3.0-rc.2 
- Create Persistent volume using pv.yaml file
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: appsody-manual-pipeline-run-pvc
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /var/lib/appsody-manual-pipeline-run-pvc
```
- Trigger a pipeline run using `java-microprofile-build-push-deploy-pipeline`, after it's done buildiing.  I see that the PV is still Bound and not released

```
$ oc get pv
NAME                               CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                                                   STORAGECLASS   REASON    AGE
appsody-manual-pipeline-run-pvc    5Gi        RWO            Recycle          Bound       kabanero/che-jmp-webhook-1573513014-gcn78-r-hjhfh-pvc                            35m
                           14m
$ oc get pvc
NAME                                           STATUS        VOLUME                             CAPACITY   ACCESS MODES   STORAGECLASS   AGE
che-jmp-webhook-1573513014-gcn78-r-hjhfh-pvc   Terminating   appsody-manual-pipeline-run-pvc    5Gi        RWO                           3h52m

$ oc describe pvc che-jmp-webhook-1573513014-gcn78-r-hjhfh-pvc
Name:          che-jmp-webhook-1573513014-gcn78-r-hjhfh-pvc
Namespace:     kabanero
StorageClass:  
Status:        Terminating (lasts 3h)
Volume:        appsody-manual-pipeline-run-pvc
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed=yes
               pv.kubernetes.io/bound-by-controller=yes
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      5Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Events:        <none>

```
