### ISSUE TITLE
Update to createKnativeService value in app-deploy.yaml does not apply to appsodyApplication CR

### ISSUE THREAD

**Issue by tam512** [kabanero-io/kabanero-pipelines#166]
- Use Kabanero 0.5.0-rc2 to test Java microprofile app with createKnativeService enabled
- Enabled `createKnativeService` to `true` in app-deploy.yaml to trigger a java-microprofile-build-push-deploy-pipeline-run, after the build is done running, I do not see Knative resources being created in `oc get all` output.
- Below is the settings in app-deploy.yaml file
```
spec:
  createKnativeService: true
  expose: true
```
- After the pipleline done building, `oc get appsodyApplication javamp -o yaml` output shows `createKnativeService: false`

```
# oc get appsodyApplication javamp -o yaml
apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    architecture: x86_64
    ............................
    .................
spec:
  applicationImage: image-registry.openshift-image-registry.svc:5000/svt-project3/javamp:94af9a3c168e0d42e8a1e7920aa8207cdb63ff94
  createKnativeService: false
  expose: true
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /health/live
      port: 9080
    initialDelaySeconds: 5
    periodSeconds: 2
  pullPolicy: IfNotPresent
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /health/ready
      port: 9080
    initialDelaySeconds: 5
    periodSeconds: 2
    timeoutSeconds: 1
  resourceConstraints: {}
  service:
    annotations:
      prometheus.io/scrape: "true"
    port: 9080
    type: NodePort
  stack: java-microprofile
  version: 1.0.0
status:
  conditions:
  - lastUpdateTime: "2020-01-22T14:39:19Z"
    status: "True"
    type: DependenciesSatisfied
  - lastUpdateTime: "2020-01-22T14:39:19Z"
    status: "True"
    type: Reconciled
```
