### ISSUE TITLE
Pipeline validation does not work for multiple stacks

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/kabanero-pipelines#172]
Kabanero 0.5 has ability to define multiple stacks with different versions. But pipeline is not able to validate multiple stacks correctly.

￼￼￼Below is an example, although this stack is active, pipeline validation is failing.
```
spec:
  desiredState: active
  name: java-microprofile
  repositoryUrl: https://github.com/kabanero-io/collections/releases/download/0.5.0-rc.3/kabanero-index.yaml
  version: 0.2.21
  versions:
  - desiredState: active
    repositoryUrl: https://github.com/kabanero-io/collections/releases/download/0.5.0-rc.3/kabanero-index.yaml
    version: 0.2.21
  - desiredState: active
    repositoryUrl: https://github.com/kabanero-io/collections/releases/download/0.2.0/kabanero-index.yaml
    version: 0.2.18
```
![image](https://user-images.githubusercontent.com/29490950/73202769-bf680d80-4109-11ea-80e0-4095119db61d.png)
