### ISSUE TITLE
0.7-rc.1 pipeline has image name 2x

### ISSUE THREAD

**Issue by dacleyra** [kabanero-io/kabanero-pipelines#270]
https://github.com/dacleyra/kabanero-operator/blob/master/tests/pipelinerun.sh

0.7-rc.1

When the image is generated to be pushed it is

image-registry.openshift-image-registry.svc:5000/kabanero/**java-microprofile/java-microprofile**

**Comment by aadeshpa** [comment]
@dacleyra : after the latest changes, now the docker image url to be provided should be `docker.io/<docker_id>` and the pipelinerun should be like below

```
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: <stack-name>-manual-pipeline-run
spec:
  params:
  - name: event-type
    value: push
  - name: event-ref
    value: refs/heads/master
  - name: docker-imagename
    value: <stack-name>-image
  - name: docker-imagetag
    value: latest
  serviceAccountName: kabanero-pipeline
  timeout: "1h0m0s"
  pipelineRef:
    name: <stack-name>-build-deploy-pl
  resources:
    - name: git-source
      resourceRef:
        name: git-source
    - name: docker-image
      resourceRef:
        name: docker-image
```

This is because we have changed the way the image name to be passed from the trigger files. Hence in case of manual pipeline run it should go as input parameters.

So in your example since you pass the docker-image with complete url with image name , hence it is concatenating the `java-microprofile` ahead of the url you gave.

cc: @kvijai82
