### ISSUE TITLE
Fail to push image when running java-websphere-traditional-build-push-pl pipeline

### ISSUE THREAD

**Issue by tam512** [kabanero-io/kabanero-pipelines#279]
In ICPA 4.1.0-rc.4/OCP 4.3, run tWAS pipeline `java-websphere-traditional-build-push-pl` fails at push image step with the following error in the pod's log:
```
error pushing image "image-registry.openshift-image-registry.svc:5000/svt-project1" to "docker://image-registry.openshift-image-registry.svc:5000/svt-project1": error copying layers and metadata from "containers-storage:[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.imagestore=/var/lib/shared,overlay.mount_program=/usr/bin/fuse-overlayfs,overlay.mountopt=nodev,metacopy=on]image-registry.openshift-image-registry.svc:5000/svt-project1:latest" to "docker://image-registry.openshift-image-registry.svc:5000/svt-project1:latest": Error trying to reuse blob sha256:5601485f01090b2ed055cfcbc1c36eb5acc39a57b80209a8d9f9ab34b2d457da at destination: unable to retrieve auth token: invalid username/password
```
This problem is not seen if using pipeline `java-websphere-traditional-build-deploy-pl`

**To Reproduce**

1. Run stack-hub-setup and stack-hub-build using cluster’s internal image registry following instruction at https://www-03preprod.ibm.com/support/knowledgecenter/SSCSJL_4.1.x/settingup.html
1. add appsody repo _tam-stacks http://kabanero-index-kabanero.apps.siamang.os.fyre.ibm.com/kabanero-index.yaml_
1. create tWAS hello-world app (appsody init tam-stacks/java-websphere-traditional)
1. checkin the app to github, create secret and webhook and trigger java-websphere-traditional-build-push-pl pipeline run

**Logs**
- Log from command `oc logs --all-containers java-websphere-traditional-build-push-pl-run-2dg85-build--l5dzb`
[twas-build-push-pipeline-pod.log.zip](https://github.com/kabanero-io/kabanero-pipelines/files/4382908/twas-build-push-pipeline-pod.log.zip)

**Comment by marikaj123** [comment]
The fix is needed to go in the current Master stream and in Kabanero release 0.6.0

**Comment by marikaj123** [comment]
Hi @kvijai82 - Please update us with the decision towards providing the fix in Kabanero 0.6.0, as an iFix.

**Comment by kvijai82** [comment]
Have a fix and in the process of testing it.  Should have a new 0.6.0
release available today.

**Comment by marikaj123** [comment]
@tam512 - Please let us know if the fix has pass verificstion testing: https://github.com/kabanero-io/kabanero-pipelines/releases/tag/0.6.2.

**Comment by kvijai82** [comment]
@tam512 Fix is in 0.6.2 pipelines release.  Please test it out and close once fix is verified.  You can update the Kabanero CR with this pipeline release to test

```
    pipelines:
    - gitRelease: {}
      https:
        url: https://github.com/kabanero-io/kabanero-pipelines/releases/download/0.6.2/default-kabanero-pipelines.tar.gz
      id: default
      sha256: bfda9cd86f6054e8f58304c283ca571ec80435880a875ae1ade02c8ec24756ea
```

**Comment by tam512** [comment]
Verified in ICPA 4.1.0 with the following pipelines
```
stacks:
      pipelines:
      - https:
          url: https://github.com/kabanero-io/kabanero-pipelines/releases/download/0.6.2/default-kabanero-pipelines.tar.gz
        id: default
        sha256: bfda9cd86f6054e8f58304c283ca571ec80435880a875ae1ade02c8ec24756ea
      repositories:
      - https:
          url: http://kabanero-index-kabanero.apps.siamang.os.fyre.ibm.com/kabanero-index.yaml
        name: central
```
- trigger build `java-websphere-traditional-build-push-pl-run-nwmt8` and it passes
```
# oc logs --all-containers java-websphere-traditional-build-push-pl-run-nwmt8-build--qrqnq
............
......................
Successfully pushed //image-registry.openshift-image-registry.svc:5000/svt-project1/twas-helloworld:0e3f28361e09020019b036ea55ac6c09b996a98c@sha256:5a4bb37b0d48a6861ba37207212b1c625d0180de5643c8c22030ad4661eb2328
```
