### ISSUE TITLE
The CRD is not updating the StackId

### ISSUE THREAD

**Issue by oiricaud** [kabanero-io/kabanero-pipelines#395]
Kabanero: 0.6.1

In the [docs](https://kabanero.io/guides/working-with-pipelines/#creating-and-updating-your-own-tasks-and-pipelines) we can see
---
"When the product operator activates the CRD, it associates the pipelines in the pipelines archive with each of the stacks in the stack hub. The default pipelines are intended to work with all the stacks in the stack hub in the previous example. All of the pipeline-related resources (such as the tasks, trigger bindings, and pipelines) prefix the name of the resource with the keyword StackId. When the operator activates these resources, it replaces the keyword with the name of the stack it is activating."

But upon creating a new pipeline resource such as 
```yaml
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: StackId-mcm-pl-pullrequest-binding
```

I get 
``` bash
\"StackId-mcm-pl\" is invalid: metadata.name: Invalid value: \"StackId-mcm-pl\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')} 
```

It appears the Regex only accepts lower case letters. 

I added a new pipeline object with id `nodejs-mcm` in my CRD

``` yaml

    stacks:
      repositories:
      - https:
          name: central
          url: https://github.com/kabanero-io/kabanero-stack-hub/releases/download/0.6.3/kabanero-stack-hub-index.yaml
      - https:
          name: custom-node-stack
          url: https://github.com/odrodrig/custom-node-stack/releases/download/0.5.0/custom-node-stack-index.yaml
      pipelines:
      - https:
          url: https://github.com/kabanero-io/kabanero-pipelines/releases/download/0.6.1/default-kabanero-pipelines.tar.gz
        id: default
        sha256: 64aee2805d36127c2f1e0e5f0fc6fdae5cef19360c1bb506137584f3bd0988cc
      - https:
          url: https://github.com/oiricaud/devops-demo-kabanero-pipelines/releases/download/v1.31/default-kabanero-pipelines.tar.gz
        id: nodejs-mcm
        sha256: cfbe25c9650304601273fac167521a1c1c73e4ea2de2dd672d574abf0c033a9a
```

I am not sure if this is a bug or if I am missing a step, but it appears the operator is not activating these resources nor replacing the keyword name with the stack id. 

I merely edited the `kabanero.yaml` file and changed the version and included the sha256
